name: Documentation Links Check Action

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  links-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set Up Env
        run: make env
      
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Build docs
        run: make docs
      
      - name: debug
        run: |
          ls -l
          ls -l docs/build/html
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          args: --verbose --base docs/build/html --exclude-file docs/.lycheeignore --exclude-loopback --exclude-mail --no-progress "docs/build/html/**/*.html" README.rst FAQ.rst
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
